spring:
  datasource:
    url: jdbc:mysql://localhost:53306/batch?serverTimezone=UTC
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
server:
  port: 9877



events:
  queues:
    user-created-by-name-queue: user_created_by_name_queue
    user-created-record-queue: user_created_record_queue
    user-created-event-type-queue: user_created_event_type_queue

