### lesson setting 조회
GET http://localhost:8080/api/v1/group-class/22

### lesson setting 등록
POST http://localhost:8080/api/v1/group-class
Content-Type: application/json

{
  "autoPublishSettingType": "D",
  "autoPublishSettingCycle": 0,
  "autoPublishSettingPeriod": 0,
  "autoPublishSettingDay": "",
  "autoPublishSettingTime": "",
  "autoCancelSettingCount": "",
  "autoCancelSettingTime": 0
}

### lesson setting 수정
PUT http://localhost:8080/api/v1/group-class
Content-Type: application/json

{
  "seqGroupClassSetting": 2,
  "autoPublishSettingType": "D",
  "autoPublishSettingCycle": 0,
  "autoPublishSettingPeriod": 0,
  "autoPublishSettingDay": "",
  "autoPublishSettingTime": "",
  "autoCancelSettingCount": "",
  "autoCancelSettingTime": 0
}

### lesson setting 삭제
DELETE http://localhost:8080/api/v1/group-class/23
Content-Type: application/json