### saveOrUpdateReservation
POST http://localhost:8080/reservations
Content-Type: application/json

{
  "id": "1",
  "name": "JunSeok",
  "roomNumber": "101"
}

### updateMultipleReservations
POST http://localhost:8080/reservations/all
Content-Type: application/json

[
  {
    "id": "1",
    "name": "JunSeok001",
    "roomNumber": "10101"
  },
  {
    "id": "2",
    "name": "JunSeok002",
    "roomNumber": "10202"
  },
  {
    "id": "3",
    "name": "JunSeok003",
    "roomNumber": "10303"
  }
]

### findReservationById
GET http://localhost:8080/reservations/1

### deleteReservationById
DELETE http://localhost:8080/reservations/1
